apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello
        image: "samber/hello-world-nodejs"
        ports:
        - containerPort: 8080
