/*
** EPITECH PROJECT, 2020
** B-CPP-501-PAR-5-1-rtype-aurele.auboin
** File description:
** Entity ChangeMe
*/

#ifndef SERVERENTITYCHANGEME_HPP_
#define SERVERENTITYCHANGEME_HPP_

namespace rtype {
    namespace entity {

        class ChangeMe {
            private:
            protected:
            public:
                ChangeMe() = default;
                virtual ~ChangeMe() = default;
        };

    }
}

#endif /* !SERVERENTITYCHANGEME_HPP_ */
