/*
** EPITECH PROJECT, 2020
** PSU_strace_2019
** File description:
** tab_syscall
*/

#ifndef TAB_SYSCALL_H_
#define TAB_SYSCALL_H_

typedef enum type_param_e {
    VOID,
    INT,
    PTR,
    STR,
    MOD,
    LONG,
} type_param_t;

typedef struct tab_syscall_s
{
    char *sys_name;
    char nbr_param : 7;
    type_param_t param_type[6];
    type_param_t ret_type;
} tab_syscall_t;

static const tab_syscall_t tab_32[385] = {
    {"restart_syscall", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"exit", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fork", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"read", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"write", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"open", 3, {STR, INT, MOD, VOID, VOID, VOID}, INT},
    {"close", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"waitpid", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"creat", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"link", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"unlink", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"execve", 3, {STR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"chdir", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"time", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mknod", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"chmod", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"lchown", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"break", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"oldlstat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"lseek", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getpid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mount", 5, {STR, STR, STR, INT, PTR, VOID}, INT},
    {"umount", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setuid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getuid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"stime", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ptrace", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"alarm", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"oldfstat", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"pause", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"utime", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"stty", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"gtty", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"access", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"nice", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ftime", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sync", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"kill", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"rename", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"mkdir", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"rmdir", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"dup", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"pipe", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"times", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"prof", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"brk", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, LONG},
    {"setgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getgid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"signal", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"geteuid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getegid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"acct", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"umount2", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"lock", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ioctl", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"fcntl", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"mpx", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setpgid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"ulimit", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"oldolduname", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"umask", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"chroot", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ustat", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"dup2", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getppid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getpgrp", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setsid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sigaction", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"sgetmask", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ssetmask", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setreuid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"setregid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"sigsuspend", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sigpending", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sethostname", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"setrlimit", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getrlimit", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getrusage", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"gettimeofday", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"settimeofday", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getgroups", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"setgroups", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"select", 5, {INT, PTR, PTR, PTR, PTR, VOID}, INT},
    {"symlink", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"oldlstat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"readlink", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"uselib", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"swapon", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"reboot", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"readdir", 3, {INT, PTR, INT, VOID, VOID, VOID}, PTR},
    {"mmap", 6, {PTR, INT, INT, INT, INT, INT}, PTR},
    {"munmap", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"truncate", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"ftruncate", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"fchmod", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"fchown", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getpriority", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"setpriority", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"profil", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"statfs", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstatfs", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"ioperm", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"socketcall", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"syslog", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"setitimer", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"getitimer", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"stat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"lstat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstat", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"olduname", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"iopl", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"vhangup", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"idle", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"vm86old", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"wait4", 4, {INT, PTR, INT, PTR, VOID, VOID}, INT},
    {"swapoff", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sysinfo", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ipc", 6, {INT, INT, INT, INT, PTR, INT}, INT},
    {"fsync", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sigreturn", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"clone", 5, {INT, INT, PTR, PTR, INT, VOID}, INT},
    {"setdomainname", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"uname", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"modify_ldt", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"adjtimex", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mprotect", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"sigprocmask", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"create_module", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"init_module", 3, {PTR, INT, STR, VOID, VOID, VOID}, INT},
    {"delete_module", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"get_kernel_syms", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"quotactl", 4, {INT, STR, INT, PTR, VOID, VOID}, INT},
    {"getpgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fchdir", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"bdflush", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"sysfs", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"personality", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"afs_syscall", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"setfsuid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setfsgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"_llseek", 5, {INT, INT, INT, PTR, INT, VOID}, INT},
    {"getdents", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"_newselect", 5, {INT, PTR, PTR, PTR, PTR, VOID}, INT},
    {"flock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"msync", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"readv", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"writev", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"getsid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fdatasync", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"_sysctl", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"mlock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"munlock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"mlockall", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"munlockall", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_setparam", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sched_getparam", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sched_setscheduler", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"sched_getscheduler", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_yield", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_get_priority_max", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_get_priority_min", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_rr_get_interval", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"nanosleep", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mremap", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"setresuid", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresuid", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"vm86", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"query_module", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"poll", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"nfsservctl", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"setresgid", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresgid", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"prctl", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"rt_sigreturn", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"rt_sigaction", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigprocmask", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigpending", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"rt_sigtimedwait", 4, {PTR, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigqueueinfo", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"rt_sigsuspend", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"pread64", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"pwrite64", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"chown", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"getcwd", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"capget", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"capset", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"sigaltstack", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sendfile", 4, {INT, INT, PTR, INT, VOID, VOID}, INT},
    {"getpmsg", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"putpmsg", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"vfork", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ugetrlimit", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"mmap2", 6, {PTR, INT, INT, INT, INT, INT}, PTR},
    {"truncate64", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"ftruncate64", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"stat64", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"lstat64", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstat64", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"lchown32", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"getuid32", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getgid32", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"geteuid32", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getegid32", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setreuid32", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"setregid32", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getgroups32", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"setgroups32", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fchown32", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"setresuid32", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresuid32", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"setresgid32", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresgid32", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"chown32", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"setuid32", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setgid32", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setfsuid32", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setfsgid32", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"pivot_root", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"mincore", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"madvise", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"getdents64", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"fcntl32", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"gettid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"readahead", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"setxattr", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"lsetxattr", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"fsetxattr", 5, {INT, STR, PTR, INT, INT, VOID}, INT},
    {"getxattr", 4, {STR, STR, PTR, INT, VOID, VOID}, INT},
    {"lgetxattr", 4, {STR, STR, PTR, INT, VOID, VOID}, INT},
    {"fgetxattr", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"listxattr", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"llistxattr", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"flistxattr", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"removexattr", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"lremovexattr", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"fremovexattr", 2, {INT, STR, VOID, VOID, VOID, VOID}, INT},
    {"tkill", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"sendfile", 4, {INT, INT, PTR, INT, VOID, VOID}, INT},
    {"futex", 6, {PTR, INT, INT, PTR, PTR, INT}, INT},
    {"sched_setaffinity", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"sched_getaffinity", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"set_thread_area", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"get_thread_area", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"io_setup", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"io_destroy", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"io_getevents", 5, {INT, INT, INT, PTR, PTR, VOID}, INT},
    {"io_submit", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"io_cancel", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"fadvise64", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"exit_group", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"lookup_dcookie", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"epoll_create", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"epoll_ctl", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"epoll_wait", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"remap_file_pages", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"set_tid_address", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"timer_create", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"timer_settime", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"timer_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"timer_getoverrun", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"timer_delete", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"clock_settime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_getres", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_nanosleep", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"statfs64", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstatfs64", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"tgkill", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"utimes", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fadvise64_64", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"vserver", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"mbind", 6, {INT, INT, INT, PTR, INT, INT}, INT},
    {"get_mempolicy", 5, {PTR, PTR, INT, INT, INT, VOID}, INT},
    {"set_mempolicy", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"mq_open", 4, {STR, INT, INT, PTR, VOID, VOID}, INT},
    {"mq_unlink", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mq_timedsend", 5, {INT, STR, INT, INT, PTR, VOID}, INT},
    {"mq_timedreceive", 5, {INT, STR, INT, PTR, PTR, VOID}, INT},
    {"mq_notify", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mq_getsetattr", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"kexec_load", 4, {INT, INT, PTR, INT, VOID, VOID}, INT},
    {"waitid", 5, {INT, INT, PTR, INT, PTR, VOID}, INT},
    {"add_key", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"request_key", 4, {STR, STR, STR, INT, VOID, VOID}, INT},
    {"keyctl", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"ioprio_set", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"ioprio_get", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"inotify_init", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"inotify_add_watch", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"inotify_rm_watch", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"migrate_pages", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"openat", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"mkdirat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"mknodat", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"fchownat", 5, {INT, STR, INT, INT, INT, VOID}, INT},
    {"futimesat", 3, {INT, STR, PTR, VOID, VOID, VOID}, INT},
    {"futimesat", 3, {INT, STR, PTR, VOID, VOID, VOID}, INT},
    {"fstatat64", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"renameat", 4, {INT, STR, INT, STR, VOID, VOID}, INT},
    {"linkat", 5, {INT, STR, INT, STR, INT, VOID}, INT},
    {"symlinkat", 3, {STR, INT, STR, VOID, VOID, VOID}, INT},
    {"readlinkat", 4, {INT, STR, STR, INT, VOID, VOID}, INT},
    {"fchmodat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"faccessat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"pselect6", 6, {INT, PTR, PTR, PTR, PTR, PTR}, INT},
    {"ppoll", 5, {PTR, INT, PTR, PTR, INT, VOID}, INT},
    {"unshare", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"set_robust_list", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"get_robust_list", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"splice", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"sync_file_range", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"tee", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"vmsplice", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"move_pages", 6, {INT, INT, PTR, PTR, PTR, INT}, INT},
    {"getcpu", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"epoll_pwait", 6, {INT, PTR, INT, INT, PTR, INT}, INT},
    {"utimensat", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"signalfd", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"timerfd_create", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"eventfd", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fallocate", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"timerfd_settime", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"timerfd_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"signalfd4", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"eventfd2", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"epoll_create1", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"dup3", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"pipe2", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"inotify_init1", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"preadv", 5, {INT, PTR, INT, INT, INT, VOID}, INT},
    {"pwritev", 5, {INT, PTR, INT, INT, INT, VOID}, INT},
    {"rt_tgsigqueueinfo", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"perf_event_open", 5, {PTR, INT, INT, INT, INT, VOID}, INT},
    {"recvmmsg", 5, {INT, PTR, INT, INT, PTR, VOID}, INT},
    {"fanotify_init", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"fanotify_mark", 5, {INT, INT, INT, INT, STR, VOID}, INT},
    {"prlimit64", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"name_to_handle_at", 5, {INT, STR, PTR, PTR, INT, VOID}, INT},
    {"open_by_handle_at", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"clock_adjtime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"syncfs", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sendmmsg", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"setns", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"process_vm_readv", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"process_vm_writev", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"kcmp", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"finit_module", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"sched_setattr", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"sched_getattr", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"renameat2", 5, {INT, STR, INT, STR, INT, VOID}, INT},
    {"seccomp", 3, {INT, INT, STR, VOID, VOID, VOID}, INT},
    {"getrandom", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"memfd_create", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"bpf", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"execveat", 5, {INT, STR, PTR, PTR, INT, VOID}, INT},
    {"socket", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"socketpair", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"bind", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"connect", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"listen", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"accept4", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"getsockopt", 5, {INT, INT, INT, STR, PTR, VOID}, INT},
    {"setsockopt", 5, {INT, INT, INT, STR, INT, VOID}, INT},
    {"getsockname", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"getpeername", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"sendto", 6, {INT, PTR, INT, INT, PTR, INT}, INT},
    {"sendmsg", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"recvfrom", 6, {INT, PTR, INT, INT, PTR, PTR}, INT},
    {"recvmsg", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"shutdown", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"userfaultfd", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"membarrier", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"mlock2", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"copy_file_range", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"preadv2", 6, {INT, PTR, INT, INT, INT, INT}, INT},
    {"pwritev2", 6, {INT, PTR, INT, INT, INT, INT}, INT},
    {"pkey_mprotect", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"pkey_alloc", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"pkey_free", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"statx", 5, {INT, STR, INT, INT, PTR, VOID}, INT},
    {"arch_prctl", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"io_pgetevents", 5, {INT, INT, INT, PTR, PTR, VOID}, INT},
};


static const tab_syscall_t tab_64[367] = {
    {"read", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"write", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"open", 3, {STR, INT, MOD, VOID, VOID, VOID}, INT},
    {"close", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"stat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstat", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"lstat", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"poll", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"lseek", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"mmap", 6, {PTR, INT, INT, INT, INT, INT}, PTR},
    {"mprotect", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"munmap", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"brk", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, LONG},
    {"rt_sigaction", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigprocmask", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigreturn", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"ioctl", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"pread64", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"pwrite64", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"readv", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"writev", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"access", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"pipe", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"select", 5, {INT, PTR, PTR, PTR, PTR, VOID}, INT},
    {"sched_yield", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mremap", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"msync", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"mincore", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"madvise", 3, {PTR, INT, INT, VOID, VOID, VOID}, INT},
    {"shmget", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"shmat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"shmctl", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"dup", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"dup2", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"pause", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"nanosleep", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getitimer", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"alarm", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setitimer", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"getpid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sendfile", 4, {INT, INT, PTR, INT, VOID, VOID}, INT},
    {"socket", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"connect", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"accept", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"sendto", 6, {INT, PTR, INT, INT, PTR, INT}, INT},
    {"recvfrom", 6, {INT, PTR, INT, INT, PTR, PTR}, INT},
    {"sendmsg", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"recvmsg", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"shutdown", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"bind", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"listen", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getsockname", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"getpeername", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"socketpair", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"setsockopt", 5, {INT, INT, INT, STR, INT, VOID}, INT},
    {"getsockopt", 5, {INT, INT, INT, STR, PTR, VOID}, INT},
    {"clone", 5, {INT, INT, PTR, PTR, INT, VOID}, INT},
    {"fork", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"vfork", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"execve", 3, {STR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"exit", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"wait4", 4, {INT, PTR, INT, PTR, VOID, VOID}, INT},
    {"kill", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"uname", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"semget", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"semop", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"semctl", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"shmdt", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"msgget", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"msgsnd", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"msgrcv", 5, {INT, PTR, INT, INT, INT, VOID}, INT},
    {"msgctl", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"fcntl", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"flock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"fsync", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fdatasync", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"truncate", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"ftruncate", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getdents", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"getcwd", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"chdir", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fchdir", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"rename", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"mkdir", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"rmdir", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"creat", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"link", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"unlink", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"symlink", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"readlink", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"chmod", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"fchmod", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"chown", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"fchown", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"lchown", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"umask", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"gettimeofday", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getrlimit", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"getrusage", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sysinfo", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"times", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ptrace", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"getuid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"syslog", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"getgid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setuid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"geteuid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getegid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setpgid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getppid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getpgrp", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setsid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setreuid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"setregid", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getgroups", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"setgroups", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"setresuid", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresuid", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"setresgid", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getresgid", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"getpgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setfsuid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setfsgid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"getsid", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"capget", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"capset", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"rt_sigpending", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"rt_sigtimedwait", 4, {PTR, PTR, PTR, INT, VOID, VOID}, INT},
    {"rt_sigqueueinfo", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"rt_sigsuspend", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"sigaltstack", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"utime", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mknod", 3, {STR, INT, INT, VOID, VOID, VOID}, INT},
    {"uselib", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"personality", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ustat", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"statfs", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"fstatfs", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sysfs", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"getpriority", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"setpriority", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"sched_setparam", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sched_getparam", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"sched_setscheduler", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"sched_getscheduler", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_get_priority_max", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_get_priority_min", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sched_rr_get_interval", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mlock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"munlock", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"mlockall", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"munlockall", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"vhangup", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"modify_ldt", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"pivot_root", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"_sysctl", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"prctl", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"arch_prctl", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"adjtimex", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"setrlimit", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"chroot", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sync", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"acct", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"settimeofday", 2, {PTR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mount", 5, {STR, STR, STR, INT, PTR, VOID}, INT},
    {"umount2", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"swapon", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"swapoff", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"reboot", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"sethostname", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"setdomainname", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"iopl", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"ioperm", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"create_module", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"init_module", 3, {PTR, INT, STR, VOID, VOID, VOID}, INT},
    {"delete_module", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"get_kernel_syms", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"query_module", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"quotactl", 4, {INT, STR, INT, PTR, VOID, VOID}, INT},
    {"nfsservctl", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"getpmsg", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"putpmsg", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"afs_syscall", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"tuxcall", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"security", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"gettid", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"readahead", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"setxattr", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"lsetxattr", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"fsetxattr", 5, {INT, STR, PTR, INT, INT, VOID}, INT},
    {"getxattr", 4, {STR, STR, PTR, INT, VOID, VOID}, INT},
    {"lgetxattr", 4, {STR, STR, PTR, INT, VOID, VOID}, INT},
    {"fgetxattr", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"listxattr", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"llistxattr", 3, {STR, STR, INT, VOID, VOID, VOID}, INT},
    {"flistxattr", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"removexattr", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"lremovexattr", 2, {STR, STR, VOID, VOID, VOID, VOID}, INT},
    {"fremovexattr", 2, {INT, STR, VOID, VOID, VOID, VOID}, INT},
    {"tkill", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"time", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"futex", 6, {PTR, INT, INT, PTR, PTR, INT}, INT},
    {"sched_setaffinity", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"sched_getaffinity", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"set_thread_area", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"io_setup", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"io_destroy", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"io_getevents", 5, {INT, INT, INT, PTR, PTR, VOID}, INT},
    {"io_submit", 3, {INT, INT, PTR, VOID, VOID, VOID}, INT},
    {"io_cancel", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"get_thread_area", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"lookup_dcookie", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"epoll_create", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"epoll_ctl_old", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"epoll_wait_old", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"remap_file_pages", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"getdents64", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"set_tid_address", 1, {PTR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"restart_syscall", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"semtimedop", 4, {INT, PTR, INT, PTR, VOID, VOID}, INT},
    {"fadvise64", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"timer_create", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"timer_settime", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"timer_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"timer_getoverrun", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"timer_delete", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"clock_settime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_getres", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"clock_nanosleep", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"exit_group", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"epoll_wait", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"epoll_ctl", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"tgkill", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"utimes", 2, {STR, PTR, VOID, VOID, VOID, VOID}, INT},
    {"vserver", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"mbind", 6, {INT, INT, INT, PTR, INT, INT}, INT},
    {"set_mempolicy", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"get_mempolicy", 5, {PTR, PTR, INT, INT, INT, VOID}, INT},
    {"mq_open", 4, {STR, INT, INT, PTR, VOID, VOID}, INT},
    {"mq_unlink", 1, {STR, VOID, VOID, VOID, VOID, VOID}, INT},
    {"mq_timedsend", 5, {INT, STR, INT, INT, PTR, VOID}, INT},
    {"mq_timedreceive", 5, {INT, STR, INT, PTR, PTR, VOID}, INT},
    {"mq_notify", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"mq_getsetattr", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"kexec_load", 4, {INT, INT, PTR, INT, VOID, VOID}, INT},
    {"waitid", 5, {INT, INT, PTR, INT, PTR, VOID}, INT},
    {"add_key", 5, {STR, STR, PTR, INT, INT, VOID}, INT},
    {"request_key", 4, {STR, STR, STR, INT, VOID, VOID}, INT},
    {"keyctl", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"ioprio_set", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"ioprio_get", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"inotify_init", 0, {VOID, VOID, VOID, VOID, VOID, VOID}, INT},
    {"inotify_add_watch", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"inotify_rm_watch", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"migrate_pages", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"openat", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"mkdirat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"mknodat", 4, {INT, STR, INT, INT, VOID, VOID}, INT},
    {"fchownat", 5, {INT, STR, INT, INT, INT, VOID}, INT},
    {"futimesat", 3, {INT, STR, PTR, VOID, VOID, VOID}, INT},
    {"newfstatat", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"unlinkat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"renameat", 4, {INT, STR, INT, STR, VOID, VOID}, INT},
    {"linkat", 5, {INT, STR, INT, STR, INT, VOID}, INT},
    {"symlinkat", 3, {STR, INT, STR, VOID, VOID, VOID}, INT},
    {"readlinkat", 4, {INT, STR, STR, INT, VOID, VOID}, INT},
    {"fchmodat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"faccessat", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"pselect6", 6, {INT, PTR, PTR, PTR, PTR, PTR}, INT},
    {"ppoll", 5, {PTR, INT, PTR, PTR, INT, VOID}, INT},
    {"unshare", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"set_robust_list", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"get_robust_list", 3, {INT, PTR, PTR, VOID, VOID, VOID}, INT},
    {"splice", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"tee", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"sync_file_range", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"vmsplice", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"move_pages", 6, {INT, INT, PTR, PTR, PTR, INT}, INT},
    {"utimensat", 4, {INT, STR, PTR, INT, VOID, VOID}, INT},
    {"epoll_pwait", 6, {INT, PTR, INT, INT, PTR, INT}, INT},
    {"signalfd", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"timerfd_create", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"eventfd", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"fallocate", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"timerfd_settime", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"timerfd_gettime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"accept4", 4, {INT, PTR, PTR, INT, VOID, VOID}, INT},
    {"signalfd4", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"eventfd2", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"epoll_create1", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"dup3", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"pipe2", 2, {PTR, INT, VOID, VOID, VOID, VOID}, INT},
    {"inotify_init1", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"preadv", 5, {INT, PTR, INT, INT, INT, VOID}, INT},
    {"pwritev", 5, {INT, PTR, INT, INT, INT, VOID}, INT},
    {"rt_tgsigqueueinfo", 4, {INT, INT, INT, PTR, VOID, VOID}, INT},
    {"perf_event_open", 5, {PTR, INT, INT, INT, INT, VOID}, INT},
    {"recvmmsg", 5, {INT, PTR, INT, INT, PTR, VOID}, INT},
    {"fanotify_init", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"fanotify_mark", 5, {INT, INT, INT, INT, STR, VOID}, INT},
    {"prlimit64", 4, {INT, INT, PTR, PTR, VOID, VOID}, INT},
    {"name_to_handle_at", 5, {INT, STR, PTR, PTR, INT, VOID}, INT},
    {"open_by_handle_at", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"clock_adjtime", 2, {INT, PTR, VOID, VOID, VOID, VOID}, INT},
    {"syncfs", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"sendmmsg", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"setns", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"getcpu", 3, {PTR, PTR, PTR, VOID, VOID, VOID}, INT},
    {"process_vm_readv", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"process_vm_writev", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"kcmp", 5, {INT, INT, INT, INT, INT, VOID}, INT},
    {"finit_module", 3, {INT, STR, INT, VOID, VOID, VOID}, INT},
    {"sched_setattr", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"sched_getattr", 4, {INT, PTR, INT, INT, VOID, VOID}, INT},
    {"renameat2", 5, {INT, STR, INT, STR, INT, VOID}, INT},
    {"seccomp", 3, {INT, INT, STR, VOID, VOID, VOID}, INT},
    {"getrandom", 6, {PTR, PTR, PTR, PTR, PTR, PTR}, INT},
    {"memfd_create", 2, {STR, INT, VOID, VOID, VOID, VOID}, INT},
    {"kexec_file_load", 5, {INT, INT, INT, STR, INT, VOID}, INT},
    {"bpf", 3, {INT, PTR, INT, VOID, VOID, VOID}, INT},
    {"execveat", 5, {INT, STR, PTR, PTR, INT, VOID}, INT},
    {"userfaultfd", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"membarrier", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"mlock2", 3, {INT, INT, INT, VOID, VOID, VOID}, INT},
    {"copy_file_range", 6, {INT, PTR, INT, PTR, INT, INT}, INT},
    {"preadv2", 6, {INT, PTR, INT, INT, INT, INT}, INT},
    {"pwritev2", 6, {INT, PTR, INT, INT, INT, INT}, INT},
    {"pkey_mprotect", 4, {INT, INT, INT, INT, VOID, VOID}, INT},
    {"pkey_alloc", 2, {INT, INT, VOID, VOID, VOID, VOID}, INT},
    {"pkey_free", 1, {INT, VOID, VOID, VOID, VOID, VOID}, INT},
    {"statx", 5, {INT, STR, INT, INT, PTR, VOID}, INT},
    {"io_pgetevents", 5, {INT, INT, INT, PTR, PTR, VOID}, INT},
};

typedef struct message_errno_s
{
    char *type_name;
    char *message;
} message_errno_t;

static const message_errno_t tab_errno[129] = {
    {"EPERM", "Operation not permitted"},
    {"ENOENT", "No such file or directory"},
    {"ESRCH", "No such process"},
    {"EINTR", "Interrupted system call"},
    {"EIO", "I/O error"},
    {"ENXIO", "No such device or address"},
    {"E2BIG", "Argument list too long"},
    {"ENOEXEC", "Exec format error"},
    {"EBADF", "Bad file number"},
    {"ECHILD", "No child processes"},
    {"EAGAIN", "Try again"},
    {"ENOMEM", "Out of memory"},
    {"EACCES", "Permission denied"},
    {"EFAULT", "Bad address"},
    {"ENOTBLK", "Block device required"},
    {"EBUSY", "Device or resource busy"},
    {"EEXIST", "File exists"},
    {"EXDEV", "Cross-device link"},
    {"ENODEV", "No such device"},
    {"ENOTDIR", "Not a directory"},
    {"EISDIR", "Is a directory"},
    {"EINVAL", "Invalid argument"},
    {"ENFILE", "File table overflow"},
    {"EMFILE", "Too many open files"},
    {"ENOTTY", "Not a typewriter"},
    {"ETXTBSY", "Text file busy"},
    {"EFBIG", "File too large"},
    {"ENOSPC", "No space left on device"},
    {"ESPIPE", "Illegal seek"},
    {"EROFS", "Read-only file system"},
    {"EMLINK", "Too many links"},
    {"EPIPE", "Broken pipe"},
    {"EDOM", "Math argument out of domain of func"},
    {"ERANGE", "Math result not representable"},
    {"EDEADLK", "Resource deadlock would occur"},
    {"ENAMETOOLONG", "File name too long"},
    {"ENOLCK", "No record locks available"},
    {"ENOSYS", "Function not implemented"},
    {"ENOTEMPTY", "Directory not empty"},
    {"ELOOP", "Too many symbolic links encountered"},
    {"ENOMSG", "No message of desired type"},
    {"EIDRM", "Identifier removed"},
    {"ECHRNG", "Channel number out of range"},
    {"EL2NSYNC", "Level 2 not synchronized"},
    {"EL3HLT", "Level 3 halted"},
    {"EL3RST", "Level 3 reset"},
    {"ELNRNG", "Link number out of range"},
    {"EUNATCH", "Protocol driver not attached"},
    {"ENOCSI", "No CSI structure available"},
    {"EL2HLT", "Level 2 halted"},
    {"EBADE", "Invalid exchange"},
    {"EBADR", "Invalid request descriptor"},
    {"EXFULL", "Exchange full"},
    {"ENOANO", "No anode"},
    {"EBADRQC", "Invalid request code"},
    {"EBADSLT", "Invalid slot"},
    {"EBFONT", "Bad font file format"},
    {"ENOSTR", "Device not a stream"},
    {"ENODATA", "No data available"},
    {"ETIME", "Timer expired"},
    {"ENOSR", "Out of streams resources"},
    {"ENONET", "Machine is not on the network"},
    {"ENOPKG", "Package not installed"},
    {"EREMOTE", "Object is remote"},
    {"ENOLINK", "Link has been severed"},
    {"EADV", "Advertise error"},
    {"ESRMNT", "Srmount error"},
    {"ECOMM", "Communication error on send"},
    {"EPROTO", "Protocol error"},
    {"EMULTIHOP", "Multihop attempted"},
    {"EDOTDOT", "RFS specific error"},
    {"EBADMSG", "Not a data message"},
    {"EOVERFLOW", "Value too large for defined data type"},
    {"ENOTUNIQ", "Name not unique on network"},
    {"EBADFD", "File descriptor in bad state"},
    {"EREMCHG", "Remote address changed"},
    {"ELIBACC", "Can not access a needed shared library"},
    {"ELIBBAD", "Accessing a corrupted shared library"},
    {"ELIBSCN", ".lib section in a.out corrupted"},
    {"ELIBMAX", "Attempting to link in too many shared libraries"},
    {"ELIBEXEC", "Cannot exec a shared library directly"},
    {"EILSEQ", "Illegal byte sequence"},
    {"ERESTART", "Interrupted system call should be restarted"},
    {"ESTRPIPE", "Streams pipe error"},
    {"EUSERS", "Too many users"},
    {"ENOTSOCK", "Socket operation on non-socket"},
    {"EDESTADDRREQ", "Destination address required"},
    {"EMSGSIZE", "Message too long"},
    {"EPROTOTYPE", "Protocol wrong type for socket"},
    {"ENOPROTOOPT", "Protocol not available"},
    {"EPROTONOSUPPORT", "Protocol not supported"},
    {"ESOCKTNOSUPPORT", "Socket type not supported"},
    {"EOPNOTSUPP", "Operation not supported on transport endpoint"},
    {"EPFNOSUPPORT", "Protocol family not supported"},
    {"EAFNOSUPPORT", "Address family not supported by protocol"},
    {"EADDRINUSE", "Address already in use"},
    {"EADDRNOTAVAIL", "Cannot assign requested address"},
    {"ENETDOWN", "Network is down"},
    {"ENETUNREACH", "Network is unreachable"},
    {"ENETRESET", "Network dropped connection because of reset"},
    {"ECONNABORTED", "Software caused connection abort"},
    {"ECONNRESET", "Connection reset by peer"},
    {"ENOBUFS", "No buffer space available"},
    {"EISCONN", "Transport endpoint is already connected"},
    {"ENOTCONN", "Transport endpoint is not connected"},
    {"ESHUTDOWN", "Cannot send after transport endpoint shutdown"},
    {"ETOOMANYREFS", "Too many references: cannot splice"},
    {"ETIMEDOUT", "Connection timed out"},
    {"ECONNREFUSED", "Connection refused"},
    {"EHOSTDOWN", "Host is down"},
    {"EHOSTUNREACH", "No route to host"},
    {"EALREADY", "Operation already in progress"},
    {"EINPROGRESS", "Operation now in progress"},
    {"ESTALE", "Stale NFS file handle"},
    {"EUCLEAN", "Structure needs cleaning"},
    {"ENOTNAM", "Not a XENIX named type file"},
    {"ENAVAIL", "No XENIX semaphores available"},
    {"EISNAM", "Is a named type file"},
    {"EREMOTEIO", "Remote I/O error"},
    {"EDQUOT", "Quota exceeded"},
    {"ENOMEDIUM", "No medium found"},
    {"EMEDIUMTYPE", "Wrong medium type"},
    {"ECANCELED", "Operation Canceled"},
    {"ENOKEY", "Required key not available"},
    {"EKEYEXPIRED", "Key has expired"},
    {"EKEYREVOKED", "Key has been revoked"},
    {"EKEYREJECTED", "Key was rejected by service"},
    {"EOWNERDEAD", "Owner died"},
    {"ENOTRECOVERABLE", "State not recoverable"},
};


#endif /* !TAB_SYSCALL_H_ */
