##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Write a Makefile that compiles your libmy.
##

NAME	=	do-op

all:	$(NAME)

$(NAME):
	gcc -o $(NAME) *.c

clean:
	rm -f *.o
	rm -f *~

fclean:	clean
	rm -f $(NAME)

re:	fclean all
