/*
** EPITECH PROJECT, 2020
** B-CPP-501-PAR-5-1-rtype-aurele.auboin
** File description:
** Entity ChangeMe
*/

#ifndef COMMONENTITYCHANGEME_HPP_
#define COMMONENTITYCHANGEME_HPP_

namespace rtype {
    namespace entity {

        class ChangeMe
        {
            private:
            protected:
            public:
                ChangeMe() = default;
                virtual ~ChangeMe() = default;
        };

    }
}

#endif /* !COMMONENTITYCHANGEME_HPP_ */
