##
## EPITECH PROJECT, 2020
## Zappy
## File description:
## Makefile Zappy with Unit tests
##

all:
	g++ ./main.cpp -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-system -lm

fclean:
	rm -f a.out

re:	fclean all

.PHONY:	all fclean re
